r = 8;
a = 13; b = 23;
u_vals = linspace(0, pi/2, 100);
theta_vals = linspace(-pi/2, pi/2, 50);

[X, Y, Z] = deal(zeros(length(theta_vals), length(u_vals)));

for j = 1:length(u_vals)
    u = u_vals(j);

    c = [a*sin(u); b*(1 - cos(u)); 0];

    dc = [a*cos(u); b*sin(u); 0];
    t_hat = dc / norm(dc);

    if abs(dot(t_hat, [0;0;1])) < 0.99
        v = [0; 0; 1];
    else
        v = [0; 1; 0];
    end
    n1 = cross(t_hat, v); n1 = n1 / norm(n1);
    n2 = cross(t_hat, n1);

    for i = 1:length(theta_vals)
        theta = theta_vals(i);
        pt = c - r * n1 + r*cos(theta)*n1 + r*sin(theta)*n2;
        X(i,j) = pt(1); Y(i,j) = pt(2); Z(i,j) = pt(3);
    end
end

figure;
surf_handle = surf(X, Y, Z, ...
    'EdgeColor', 'none', ...
    'FaceColor', [0.8 0.8 0.8], ...
    'FaceAlpha', 0.5);

axis equal;
xlabel('X'); ylabel('Y'); zlabel('Z');
title('Surface generated by sweeping a semicircle along a quarter-elliptic trajectory');
view(3)

grid on;
